### ISSUE TITLE
paren mismatch

### ISSUE THREAD

**Issue by djbender** [eapache/rainbow_parentheses.vim#4]
I'm seeing a mismatch in this code example:

```
define([           
], function () {});
```

![image](https://cloud.githubusercontent.com/assets/170351/14146237/88fe8b9e-f65c-11e5-8705-655d111a69f6.png)

My vimscript skills aren't great otherwise I'd dig into the source. Cheers!

**Comment by eapache** [comment]
I'm not
![screenshot 2016-03-30 14 44 10](https://cloud.githubusercontent.com/assets/1706826/14153461/e7f184d4-f685-11e5-81a8-0ed20010c176.png)

It may have something to do with the file-type you're working in or something else (another plugin or in your `.vimrc`) conflicting.

If you move your vimrc and other plugins out of the way can you still reproduce?

Also, to be perfectly honest, I've been using https://github.com/luochen1990/rainbow the last few months instead :)

**Comment by djbender** [comment]
I'll work on a minimal reproduction :)
