### ISSUE TITLE
Colors are loaded then disappear

### ISSUE THREAD

**Issue by merwok** [eapache/rainbow_parentheses.vim#9]
Hello!  I tried many variations of `au filetype` and `au syntax` to always load the plugin, before all other options or after, but I see the colors briefly when opening a file and then they disappear.

Looking at open bugs, I made sure to have the `syntax on` and `colorscheme` settings before the rainbow parentheses config.

I cloned the repo and installed the plugin using `set runtimepath^=~/.vim/bundle/rainbow_parentheses.vim`.

**Comment by eapache** [comment]
If you see them and then they disappear, there is probably something else you are using (some other plugin or vimrc setting) that is overriding it.

Honestly I've switched to https://github.com/luochen1990/rainbow now.

**Comment by merwok** [comment]
That other one works.  Thanks!
